### ISSUE TITLE
Update lessons to use 'super dirty' gapminder dataset

### ISSUE THREAD

**Issue by naupaka** [Reproducible-Science-Curriculum/organization-RR-Jupyter#18]
Can download here: https://github.com/Reproducible-Science-Curriculum/data-exploration-RR-Jupyter/blob/master/gapminderDataFiveYear_superDirty.txt

**Comment by dleehr** [comment]
I've added the dataset to this repo in `/data`. Is there a checklist on what's needed to update the lessons? Is it just changing file names or something deeper?

**Comment by iamciera** [comment]
This "super dirty" data set is cool, but not currently utilized in this lesson. I left it in the directory.

**Comment by hlapp** [comment]
It's still referenced and used in the [Modifying Data episode](https://reproducible-science-curriculum.github.io/organization-RR-Jupyter/04-modifying/). Although typically this episode will probably be skipped (because the important concepts are covered in the Data Exploration lesson), I think it's worth keeping, for cases that the lesson is remixed with others.

The dataset is also referenced in the [Introduction episode](https://reproducible-science-curriculum.github.io/organization-RR-Jupyter/01-introduction/), which should probably be deleted (#24).
